# Generated by Django 3.0.7 on 2020-06-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(max_length=64, verbose_name='카드이름')),
                ('cardnos', models.IntegerField(verbose_name='카드번호')),
                ('validity', models.DateField(verbose_name='유효기한')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Card',
                'ordering': ['cardname'],
            },
        ),
    ]
